In [22]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], name='Numbers')

print(s)

0    10
1    20
2    30
3    40
Name: Numbers, dtype: int64

In [23]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Bob', 'Alice'],

'Age': [25, 30, 35, None, 28, 30, None],

'City': ['New York', 'London', 'Paris','New York', 'London', 'Paris', 'Houston', ]}

df = pd.DataFrame(data)

print(df)

      Name   Age      City
0    Alice  25.0  New York
1      Bob  30.0    London
2  Charlie  35.0     Paris
3    David   NaN  New York
4      Eve  28.0    London
5      Bob  30.0     Paris
6    Alice   NaN   Houston

In [24]:
over_25 = df[df['Age'] > 25] 

print(over_25)

      Name   Age    City
1      Bob  30.0  London
2  Charlie  35.0   Paris
4      Eve  28.0  London
5      Bob  30.0   Paris

In [25]:
df

      Name   Age      City
0    Alice  25.0  New York
1      Bob  30.0    London
2  Charlie  35.0     Paris
3    David   NaN  New York
4      Eve  28.0    London
5      Bob  30.0     Paris
6    Alice   NaN   Houston

In [26]:
df['City'] = df['City'].replace('New York', 'NYC')

print(df)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David   NaN      NYC
4      Eve  28.0   London
5      Bob  30.0    Paris
6    Alice   NaN  Houston

In [27]:
#df_filled = df.fillna(0)
#df_filled
# Drop rows with any missing values

#df_dropped_na = df.dropna()
#df_dropped_na
# Handling missing values (fill with mean)

df['Age'] = df['Age'].fillna(df['Age'].mean())

print(df)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David  29.6      NYC
4      Eve  28.0   London
5      Bob  30.0    Paris
6    Alice  29.6  Houston

In [28]:
df_grouped = df.groupby('City')['Age'].mean()

print(df_grouped)

City
Houston    29.6
London     29.0
NYC        27.3
Paris      32.5
Name: Age, dtype: float64

In [29]:
df2 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Salary': [50000, 60000]})

df_merged = pd.merge(df, df2, on='Name')

print(df_merged)

    Name   Age     City  Salary
0  Alice  25.0      NYC   50000
1    Bob  30.0   London   60000
2    Bob  30.0    Paris   60000
3  Alice  29.6  Houston   50000

In [30]:
df3 = pd.DataFrame({'Name': ['David'], 'Age': [40], 'City': ['Berlin']})

df_concat = pd.concat([df, df3])

print(df_concat)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David  29.6      NYC
4      Eve  28.0   London
5      Bob  30.0    Paris
6    Alice  29.6  Houston
0    David  40.0   Berlin

In [31]:
df.drop_duplicates(inplace=True)
print(df)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David  29.6      NYC
4      Eve  28.0   London
5      Bob  30.0    Paris
6    Alice  29.6  Houston

In [32]:
df_unique_name = df.drop_duplicates(subset=['Name'])
print(df_unique_name)

      Name   Age    City
0    Alice  25.0     NYC
1      Bob  30.0  London
2  Charlie  35.0   Paris
3    David  29.6     NYC
4      Eve  28.0  London

In [33]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Bob', 'Alice'],
    'Age': [25, 30, 35, None, 28, 30, None],
    'City': ['New York', 'London', 'Paris', 'Houston', None, 'London', 'New York']
}
df = pd.DataFrame(data)

print(df)

      Name   Age      City
0    Alice  25.0  New York
1      Bob  30.0    London
2  Charlie  35.0     Paris
3    David   NaN   Houston
4      Eve  28.0      None
5      Bob  30.0    London
6    Alice   NaN  New York

In [34]:
print(df.isnull().sum())

Name    0
Age     2
City    1
dtype: int64

In [35]:
      # Selecting rows based on condition
over_25 = df[df['Age'] > 25]
print(over_25)

      Name   Age    City
1      Bob  30.0  London
2  Charlie  35.0   Paris
4      Eve  28.0    None
5      Bob  30.0  London

In [36]:
# Replacing values
df['City'] = df['City'].replace('New York', 'NYC')
print(df)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David   NaN  Houston
4      Eve  28.0     None
5      Bob  30.0   London
6    Alice   NaN      NYC

In [37]:
# Fill missing values with a specific value (e.g., 0)
df_filled = df.fillna(0)
# Drop rows with any missing values
#df_dropped_na = df.dropna()
# Handling missing values (fill with mean)

In [38]:
df_filled

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David   0.0  Houston
4      Eve  28.0        0
5      Bob  30.0   London
6    Alice   0.0      NYC

In [39]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob  30.0   London
2  Charlie  35.0    Paris
3    David  29.6  Houston
4      Eve  28.0     None
5      Bob  30.0   London
6    Alice  29.6      NYC

In [40]:
df_grouped = df.groupby('City')['Age'].mean()
print(df_grouped)

City
Houston    29.6
London     30.0
NYC        27.3
Paris      35.0
Name: Age, dtype: float64

In [41]:
df2 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Salary': [50000, 60000]})
df_merged = pd.merge(df, df2, on='Name', how='inner')
print(df_merged)

    Name   Age    City  Salary
0  Alice  25.0     NYC   50000
1    Bob  30.0  London   60000
2    Bob  30.0  London   60000
3  Alice  29.6     NYC   50000